### ISSUE TITLE
[BUG REPORT] ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by timdonovanuk** [gitmylo/audio-webui#100]
**Describe the bug**

ModuleNotFoundError: No module named '_lzma' during install.

I've looked at various results on Google but each has a completely widely different resolution path and is often for MacOS (brew install..) not Linux.

**To Reproduce**

Debian 12
Python 3.10
run run.sh

**Screenshots**

```
Traceback (most recent call last):
  File "/root/audio-webui/main.py", line 23, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/root/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/root/audio-webui/webui/modules/implementations/ttsmodels.py", line 14, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "/root/audio-webui/webui/modules/implementations/patches/bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "/root/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "/root/audio-webui/webui/ui/tabs/__init__.py", line 5, in <module>
    from .audioldm import audioldm_tab
  File "/root/audio-webui/webui/ui/tabs/audioldm.py", line 2, in <module>
    import webui.modules.implementations.audioldm as aldm
  File "/root/audio-webui/webui/modules/implementations/audioldm.py", line 5, in <module>
    import diffusers
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/__init__.py", line 63, in <module>
    from .pipelines import (
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 20, in <module>
    from .controlnet import (
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/controlnet/__init__.py", line 16, in <module>
    from .pipeline_controlnet import StableDiffusionControlNetPipeline
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 39, in <module>
    from ..stable_diffusion import StableDiffusionPipelineOutput
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/__init__.py", line 99, in <module>
    from .pipeline_stable_diffusion_k_diffusion import StableDiffusionKDiffusionPipeline
  File "/root/audio-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py", line 21, in <module>
    from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser
  File "/root/audio-webui/venv/lib/python3.10/site-packages/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/root/audio-webui/venv/lib/python3.10/site-packages/k_diffusion/config.py", line 8, in <module>
    from . import augmentation, layers, models, utils
  File "/root/audio-webui/venv/lib/python3.10/site-packages/k_diffusion/layers.py", line 8, in <module>
    from . import sampling, utils
  File "/root/audio-webui/venv/lib/python3.10/site-packages/k_diffusion/sampling.py", line 10, in <module>
    from . import utils
  File "/root/audio-webui/venv/lib/python3.10/site-packages/k_diffusion/utils.py", line 13, in <module>
    from torchvision.transforms import functional as TF
  File "/root/audio-webui/venv/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/root/audio-webui/venv/lib/python3.10/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/root/audio-webui/venv/lib/python3.10/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "/root/audio-webui/venv/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 6, in <module>
    import lzma
  File "/usr/local/lib/python3.10/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
No module named '_lzma'

```

**Comment by timdonovanuk** [comment]
I think I fixed this by:

```
apt-get install lzma
apt-get install liblzma-de
apt-get install libbz2-dev
```

And rebuilding python.
