### ISSUE TITLE
Multiple errors while installing on Google Colab

### ISSUE THREAD

**Issue by viberjet** [gitmylo/audio-webui#135]
Hello there.

I am getting multiple errors while installing [audio-webui on Google Colab

Runtime type: T4 GPU

After I ran this command:

#@title Setup { display-mode: "form" }
#@markdown 1. Clones https://github.com/gitmylo/audio-webui/
#@markdown 2. Cd's into `audio-webui`
#@markdown 3. Fix some google colab default packages
#@markdown 4. Installs packages through install.py

!git clone https://github.com/gitmylo/audio-webui/
%cd audio-webui

!pip uninstall tensorflow -y
!pip install --upgrade numpy
!python install.py --skip-venv

#########################################################################

I got the following errors while installing:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.0.6 requires tensorflow>=2.2.0, which is not installed.
cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.26.0 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.0 which is incompatible.

#########################################################################

And then after I ran this command:

#@title Launching { display-mode: "form" }
username = 'demo' #@param {type:"string"}
#@markdown Default: "`user`"
#@markdown Sets the username for the webui

#@markdown

password = '12345678' #@param {type:"string"}
#@markdown Default: "`pass`", **please change this**
#@markdown Sets the password for the webui

#@markdown

args = '' #@param {type:"string"}
#@markdown Default: empty
#@markdown Sets the other args for the webui

#@markdown

args = f'-sv -si {args} -s -u "{username}" -p "{password}"'
!python main.py $args

#########################################################################

I got the following errors:

Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Webui version: 82dcef0e059661d496d8467be2303eed3510a657 - Fri Sep 8 20:09:30 2023 +0200
Found extensions: 
Activating extensions
Preparing
Traceback (most recent call last):
  File "/content/audio-webui/main.py", line 41, in <module>
    autodebug.catcher(e)
  File "/content/audio-webui/autodebug/autodebug.py", line 79, in catcher
    raise e
  File "/content/audio-webui/main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/content/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/content/audio-webui/webui/modules/implementations/ttsmodels.py", line 10, in <module>
    import torch.cuda
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1239, in <module>
    from torch import onnx as onnx
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/__init__.py", line 12, in <module>
    from . import (  # usort:skip. Keep the order instead of sorting lexicographically
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_caffe2.py", line 4, in <module>
    from torch.onnx import symbolic_helper, symbolic_opset9 as opset9
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_helper.py", line 611, in <module>
    def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/decorcore.py", line 98, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/decorcore.py", line 147, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/_decormore.py", line 178, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/_decormore.py", line 242, in beartype_func
    func_wrapper_code = generate_code(bear_call)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/wrap/wrapmain.py", line 187, in generate_code
    code_check_return = _code_check_return(bear_call)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/wrap/wrapmain.py", line 669, in _code_check_return
    reraise_exception_placeholder(
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/error/utilerror.py", line 214, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/wrap/wrapmain.py", line 618, in _code_check_return
    ) = make_func_wrapper_code(hint_sane, bear_call.conf, cls_stack)  # type: ignore[assignment]
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "/usr/local/lib/python3.10/dist-packages/beartype/_decor/wrap/_wrapcode.py", line 86, in make_func_wrapper_code
    ) = make_check_expr(hint, conf, cls_stack)
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "/usr/local/lib/python3.10/dist-packages/beartype/_check/code/codemake.py", line 706, in make_check_expr
    die_if_hint_pep_unsupported(
  File "/usr/local/lib/python3.10/dist-packages/beartype/_util/hint/pep/utilpeptest.py", line 205, in die_if_hint_pep_unsupported
    raise BeartypeDecorHintPep484Exception(
beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).

**Comment by gitmylo** [comment]
I'm honestly not sure what causes this

**Comment by geodesius** [comment]
I have the exact same error locally on archlinux, python 3.10.13

**Comment by viberjet** [comment]
> I'm honestly not sure what causes this

I think the Google Colab has been updated python these days, because I was running it 3 days ago.

**Comment by gitmylo** [comment]
> I have the exact same error locally on archlinux, python 3.10.13

Probably a package that updated that broke other things. but i'd need to find which package it was then.

**Comment by viberjet** [comment]
> > I have the exact same error locally on archlinux, python 3.10.13
> 
> Probably a package that updated that broke other things. but i'd need to find which package it was then.

Thank you so much ❤️

**Comment by tikhonlavrev** [comment]
I got this error when install them on windows.
pip install beartype==0.15.0 on venv solve this. I don't know if it works on colab

**Comment by viberjet** [comment]
> I got this error when install them on windows. pip install beartype==0.15.0 on venv solve this. I don't know if it works on colab

Wow, it worked, Thank you so much. Gold bless you
