### ISSUE TITLE
[QUESTION] Error When Create New Workspace at train tab

### ISSUE THREAD

**Issue by tikhonlavrev** [gitmylo/audio-webui#137]
I got this error when I'm trying to create new workspace

Traceback (most recent call last):
  File "F:\audio-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "F:\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\audio-webui\webui\ui\tabs\training\rvc.py", line 112, in create_workspace
    rvc_ws.current_workspace = rvc_ws.RvcWorkspace(name).create({
  File "F:\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 66, in create
    download_base_models(data_in['vsr'])
  File "F:\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 935, in download_base_models
    huggingface_hub.hf_hub_download(repo, file, subfolder=sf,
  File "F:\audio-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\audio-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1427, in hf_hub_download
    _check_disk_space(expected_size, local_dir)
  File "F:\audio-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 975, in _check_disk_space
    target_dir_free = shutil.disk_usage(target_dir).free
  File "C:\Users\tikhonlavrev\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 1341, in disk_usage
    total, free = nt._getdiskusage(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified

Maybe it is bug?, because 2 weeks ago I didn't get this messages

**Comment by gitmylo** [comment]
I'm not sure what could be causing this, the error looks like it comes from huggingface hub trying to download a file, and checking available disk space first, but something seems to have went wrong.

You could try reinstalling, or simply deleting the `venv` folder, running the `update.bat`, then launching the webui again, it will reinstall the packages, and hopefully work this time

**Comment by tikhonlavrev** [comment]
> I'm not sure what could be causing this, the error looks like it comes from huggingface hub trying to download a file, and checking available disk space first, but something seems to have went wrong.
> 
> You could try reinstalling, or simply deleting the `venv` folder, running the `update.bat`, then launching the webui again, it will reinstall the packages, and hopefully work this time

I've tried this too, Same error after reinstalling the and run update.bat

**Comment by gitmylo** [comment]
It might have been caused by huggingface-hub updating yesterday.

https://pypi.org/project/huggingface-hub/#history

I will lock the requirement to `0.17.1` (before yesterday's update), this should work

**Comment by gitmylo** [comment]
I have just pushed a commit which could fix this issue, please update me on if it fixes this issue.

**Comment by tikhonlavrev** [comment]
> I have just pushed a commit which could fix this issue, please update me on if it fixes this issue.

Same error still happened

**Comment by gitmylo** [comment]
I will attempt to reproduce it, but since i'm on linux, and don't have quick access to a windows machine, i'm not sure if i can reproduce it, but we'll see.

**Comment by gitmylo** [comment]
I have an idea for a fix, i could monkeypatch `_check_disk_space()` on line `964` in huggingface-hub's `file_download.py` to keep the original function, but add a try catch around it. so it won't crash, a bit of a hacky fix, but it should do it.

**Comment by gitmylo** [comment]
Alright, i've pushed that change, it shouldn't crash anymore now.
