### ISSUE TITLE
[QUESTION] Error Occurs When I Try to "Copy to RVC Models"

### ISSUE THREAD

**Issue by 2BasaBoi** [gitmylo/audio-webui#149]
FileNotFoundError: [Errno 2]
After I train a RVC model, I try to "Copy to RVC Models" but once I click that, this error shows up. 

FileNotFoundError: [Errno 2] No such file or directory: 'data\\training\\RVC\\models\\workspace.json'

**Comment by gitmylo** [comment]
Huh? That is not a file it should check for, it's not even checking in the right directory?

https://github.com/gitmylo/audio-webui/blob/master/webui/ui/tabs/training/training/rvc_workspace.py#L334-L350
This code runs when the copy button is pressed, nowhere does it check for workspace.json...

Can you try again? Because i don't think this bug is possible as you describe it.

**Comment by 2BasaBoi** [comment]
Traceback (most recent call last):
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Tsubasa\Desktop\Video Things\TTS\audio-webui (1)\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 347, in copy_model
    shutil.copyfile(model_path, rvc_model_use_path)
  File "C:\Users\Tsubasa\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\training\\RVC\\models\\e_29\\.pth'

That's the exact text I get after clicking that button.

**Comment by gitmylo** [comment]
How did you create/load your workspace?

**Comment by gitmylo** [comment]
You didn't put a name? I guess i should have thought about what should happen if someone doesn't supply a name... lol

**Comment by 2BasaBoi** [comment]
Oh... I'm so stupid. I didn't even notice the name spot, sorry lol

**Comment by gitmylo** [comment]
I have added an error message in case this happens in the future.

![image](https://github.com/gitmylo/audio-webui/assets/36931363/7394b1b2-8666-475a-bd2a-98555a8d1cb6)
