### ISSUE TITLE
[BUG REPORT] Setup Error While Running Audio Webui Google Colab

### ISSUE THREAD

**Issue by lj-thirdeye** [gitmylo/audio-webui#157]
Hi all, while I'm running audio-webui's google colab notebook, in the Setup stage, I keep receiving the following failure:

`Failed to install audiocraft. Check AutoDebug output.
Traceback (most recent call last):
  File "/content/audio-webui/install.py", line 18, in <module>
    ensure_installed()
  File "/content/audio-webui/install.py", line 14, in ensure_installed
    install_requirements()
  File "/content/audio-webui/setup_tools/magicinstaller/magicinstaller.py", line 5, in install_requirements
    requirement.install_or_upgrade_if_needed()
  File "/content/audio-webui/setup_tools/magicinstaller/requirement.py", line 29, in install_or_upgrade_if_needed
    self.post_install(self.install())
  File "/content/audio-webui/setup_tools/magicinstaller/requirement.py", line 34, in post_install
    raise InstallFailException(exit_code, stdout, stderr)
autodebug.autodebug.InstallFailException: Install failed!`

I tried running this notebook on Linux and Windows, but both gave me the same failure. Has anyone met that before? I remember that a month ago the notebook run pretty smoothly, but now the setup fails. Thanks in advance for any input on this failure.

**Comment by JohnnyStreet** [comment]
Fails on Windows with run.bat on a fresh checkout also.

**Comment by gitmylo** [comment]
There's a new notebook which will show the errors that occur during install. Although it probably isn't fixed yet. I'll see if i can find more information about the issue.
