### ISSUE TITLE
[BUG REPORT] RuntimeError: CUTLASS submodule not found.

### ISSUE THREAD

**Issue by lj-thirdeye** [gitmylo/audio-webui#158]
I follow the steps to install the webui on my Windows system. When I run "run.bat", I met this error:

> STDERR:
>   error: subprocess-exited-with-error
> 
>   python setup.py egg_info did not run successfully.
>   exit code: 1
> 
>   [9 lines of output]
>   No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "C:\Users\jlmAurora\AppData\Local\Temp\pip-install-vfd6n54r\xformers_d33f228d057c4d9f8f92c2cbeb4093cf\setup.py", line 239, in <module>
>       ext_modules=get_extensions(),
>     File "C:\Users\jlmAurora\AppData\Local\Temp\pip-install-vfd6n54r\xformers_d33f228d057c4d9f8f92c2cbeb4093cf\setup.py", line 157, in get_extensions
>       raise RuntimeError(
>   RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
>   [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> Encountered error while generating package metadata.
> 
> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

After I run `pip install catlass` and `git submodule update --init --recursive`, it still returned the same error. Then I also deleted and reinstalled everything, but the error is still there. What's going on?

**Comment by gitmylo** [comment]
It might have something to do with recent changes to pytorch, as the new default CUDA version for pytorch is now 12.1 instead of 11.8. I'll lock it back to the older version, as that might fix this issue as well.

**Comment by lj-thirdeye** [comment]
> It might have something to do with recent changes to pytorch, as the new default CUDA version for pytorch is now 12.1 instead of 11.8. I'll lock it back to the older version, as that might fix this issue as well.

Okay I see. New versions do have the ability to cause issues. Thanks for the reply!
