### ISSUE TITLE
[QUESTION] last food commit?

### ISSUE THREAD

**Issue by JohnnyStreet** [gitmylo/audio-webui#159]
# Question title (e.g. Where do I download RVC models?)
question content goes here

I have not been able to use audio-webui for some time now because with a fresh checkout it won't build. There are multiple tickets open regarding it getting stuck on TTS, CUTLASS, etc. Making clean installs work should be a #1 priority but I keep seeing new features being added and I am afraid it is not going to get fixed. We are already looking at other solutions.

**Comment by JohnnyStreet** [comment]
I got farther by updating pip inside the venv and trying again but then it stops here:
```
  Traceback (most recent call last):
    File "C:\git\audio-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\git\audio-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\git\audio-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\johns\AppData\Local\Temp\pip-build-env-s2eyyi2g\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\johns\AppData\Local\Temp\pip-build-env-s2eyyi2g\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\johns\AppData\Local\Temp\pip-build-env-s2eyyi2g\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\johns\AppData\Local\Temp\pip-build-env-s2eyyi2g\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 18, in <module>
  ModuleNotFoundError: No module named 'torch'
  [end of output]
```
I tried manually installing torch from the venv and it said the requirement was already satisfied. Then I tried running again and got the same error.

**Comment by gitmylo** [comment]
I'm not sure about issues with audiocraft, but TTS has been moved out of the repository in [this branch](https://github.com/gitmylo/audio-webui/tree/TTS-extension), allowing you to skip installing it.

Audiocraft fails to install on google colab currently for a different reason. I have noticed that some people got audio-webui running again after deleting the venv folder, and switching to the other branch (which is soon to be merged, so Coqui TTS will only be available as an extension from that point)

**Comment by JohnnyStreet** [comment]
I actually managed to fix this by going into the venv and uninstalling torch the re-running. Is it possible you are using a different torch in the build process for one of the deps?

**Comment by gitmylo** [comment]
I'm running it the same way as everyone else, I just tried and was able to launch the latest version (d7db4126bb380b5b20cdb2dc0d94a5f64e727a15) without issues. The now merged TTS-extension branch also had a few fixes, although mostly in the extension part.
