### ISSUE TITLE
[BUG REPORT] TypeError: _download() missing 1 required positional argument: 'to_local_path'

### ISSUE THREAD

**Issue by PawKanarek** [gitmylo/audio-webui#164]
**Describe the bug**
I got an error after selecting model `suno/bark` from dropdown menu: 

in terminal console i have following output:
```
(audio) ➜  ~/git/audio-webui git:(master) ✗ python main.py -sv -u 'user' -p 'pass'
Checking installs and venv + autodebug checks
Python version:  3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Webui version: 4b54d93744e680a94bb0fda581f76fe5d28fc8a5 - Thu Oct 12 17:22:23 2023 +0200
Found extensions: 
Done installing/checking installs.
Activating extensions
Preparing
Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
没有发现支持的N卡, 使用MPS进行推理
exception in config_file_change_fp32: [Errno 2] No such file or directory: 'configs/32k.json'
Monkeypatching bark
Monkeypatching gradio
Launching, cuda available: False
Downloading (…)_schema%400.0.3.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.1k/13.1k [00:00<00:00, 29.6MB/s]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/raix/git/audio-webui/webui/ui/tabs/text_to_speech.py", line 52, in load_model
    loader.load_model(progress)
  File "/Users/raix/git/audio-webui/webui/modules/implementations/ttsmodels.py", line 246, in load_model
    preload_models_new(
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 669, in preload_models_new
    _ = load_model(
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 625, in load_model
    model = _load_model_f(ckpt_path, device)
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 563, in _load_model
    o._download(model_info["repo_id"], model_info["file_name"])
TypeError: _download() missing 1 required positional argument: 'to_local_path'
^CKeyboard interruption in main thread... closing server.

```

**To Reproduce**
1. Start server with command `python main.py -sv -u 'user' -p 'pass'`
2. Login into http://127.0.0.1:7860
3. Select `suno/bark` in "Text to speech" tab

**Screenshots**
![image](https://github.com/gitmylo/audio-webui/assets/15096514/9c11a01b-844d-45a5-8e88-fb5ce1101707)

**Additional context**
Working on mac m1, working on commit sha 4b54d93744e680a94bb0fda581f76fe5d28fc8a5, (current master)

**Comment by gitmylo** [comment]
So the error is on [this line](https://github.com/gitmylo/audio-webui/blob/master/webui/modules/implementations/patches/bark_generation.py#L563C9-L563C68)
But it is odd that this error would occur, since only one version of bark should be installable [as seen here](https://github.com/gitmylo/audio-webui/blob/master/setup_tools/magicinstaller/requirements/bark_package.py#L10)
It should not differ, can you compare the _download from [This commit](https://github.com/suno-ai/bark/blob/6921c9139a97d0364208407191c92ec265ef6759/bark/generation.py#L149-L151) with the one in your venv's packages folder? They should be the same

**Comment by PawKanarek** [comment]
Thanks, you gave me some insights that there might something wrong with my environment so i did full cleanup. I made new conda virtual environment with command `conda activate audio`, then I Installed python `3.10.8` with command `conda install python=3.10.8` Then I excectued `python main.py -sv -u 'user' -p 'pass'` and i got this error:
```
python main.py -sv -u 'user' -p 'pass'
Checking installs and venv + autodebug checks
Python version:  3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ]
Webui version: 98f43a2b44a703d809f65943a62009274e13c804 - Mon Oct 16 16:34:42 2023 +0200
Found extensions: 
Installed packaging!             
Installed numpy!             
Failed to install PyTorch. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://download.pytorch.org/whl/cu117
STDERR:
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
Please read the error above carefully. 
```
I figured it out that there is some problem with `torch`, to fix it i had to manually install it with command `conda install pytorch torchvision torchaudio -c pytorch`. Then i again run command `python main.py -sv -u 'user' -p 'pass'` and i got this error: 
```
(audio) ➜  ~/git/audio-webui git:(master) ✗ python main.py -sv -u 'user' -p 'pass'                 
Checking installs and venv + autodebug checks
Python version:  3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ]
Webui version: 98f43a2b44a703d809f65943a62009274e13c804 - Mon Oct 16 16:34:42 2023 +0200
Found extensions: 
Installed transformers!             
Installed diffusers!             
Installed gradio!             
Installed huggingface-hub!             
Installed audio2numpy!             
Installed bark!             
Installed sox!             
Installed audiolm!             
Installed praat-parselmouth!             
Installed pyworld!             
Installed faiss!             
Installed torchcrepe!             
Installed ffmpeg-python!             
Installed noisereduce!             
Installed demucs!             
Installed pytube!             
Installed openai-whisper!             
Installed audiocraft!             
Installed beartype!             
Done installing/checking installs.
Activating extensions
Preparing
Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
2023-10-16 19:14:38 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/Users/raix/git/audio-webui/main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/Users/raix/git/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/Users/raix/git/audio-webui/webui/modules/implementations/ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "/Users/raix/git/audio-webui/webui/ui/tabs/__init__.py", line 4, in <module>
    from .utils import utils_tab
  File "/Users/raix/git/audio-webui/webui/ui/tabs/utils.py", line 12, in <module>
    import librosa
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less
Numba needs NumPy 1.25 or less
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues
^CTraceback (most recent call last):
  File "/Users/raix/git/audio-webui/main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/Users/raix/git/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/Users/raix/git/audio-webui/webui/modules/implementations/ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "/Users/raix/git/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "/Users/raix/git/audio-webui/webui/ui/tabs/__init__.py", line 4, in <module>
    from .utils import utils_tab
  File "/Users/raix/git/audio-webui/webui/ui/tabs/utils.py", line 12, in <module>
    import librosa
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/Users/raix/miniconda3/envs/audio/lib/python3.10/site-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raix/git/audio-webui/main.py", line 44, in <module>
    autodebug.catcher(e)
  File "/Users/raix/git/audio-webui/autodebug/autodebug.py", line 77, in catcher
    input()
KeyboardInterrupt
```

So i did `pip install tensorboardX` and `conda install numpy=1.25.2 ` After this server started successfully and i could download `suno/bark` model. THANK YOU! <3
