### ISSUE TITLE
[BUG REPORT] Can't Install

### ISSUE THREAD

**Issue by navarisun1982** [gitmylo/audio-webui#171]
I have been struggling trying to install the web interface for audio-webui.
I have followed the installation process which is too easy but I always have this error, every time I do clean installation, and the same error :

Preparing
2023-11-01 01:28:40 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-11-01 01:28:40 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2023-11-01 01:28:40 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
16系/10系显卡和P40强制单精度
exception in config_file_change_fp32: [Errno 2] No such file or directory: 'configs/32k.json'
Traceback (most recent call last):
  File "D:\audio-webui\main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "D:\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "D:\audio-webui\webui\modules\implementations\ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "D:\audio-webui\webui\modules\implementations\patches\bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "D:\audio-webui\webui\modules\implementations\patches\bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "D:\audio-webui\webui\ui\tabs\__init__.py", line 8, in <module>
    from .audiocraft import audiocraft_tab
  File "D:\audio-webui\webui\ui\tabs\audiocraft.py", line 2, in <module>
    import webui.modules.implementations.audiocraft as acrft
  File "D:\audio-webui\webui\modules\implementations\audiocraft.py", line 5, in <module>
    from audiocraft.models import MusicGen
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\__init__.py", line 24, in <module>
    from . import data, modules, models
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\data\__init__.py", line 10, in <module>
    from . import audio, audio_dataset, info_audio_dataset, music_dataset, sound_dataset
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\data\info_audio_dataset.py", line 19, in <module>
    from ..modules.conditioners import SegmentWithAttributes, ConditioningAttributes
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\modules\conditioners.py", line 35, in <module>
    from ..quantization import ResidualVectorQuantizer
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\quantization\__init__.py", line 8, in <module>
    from .vq import ResidualVectorQuantizer
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\quantization\vq.py", line 13, in <module>
    from .core_vq import ResidualVectorQuantization
  File "D:\audio-webui\venv\lib\site-packages\audiocraft\quantization\core_vq.py", line 10, in <module>
    import flashy
  File "D:\audio-webui\venv\lib\site-packages\flashy\__init__.py", line 11, in <module>
    from . import distrib, adversarial
ImportError: cannot import name 'distrib' from partially initialized module 'flashy' (most likely due to a circular import) (D:\audio-webui\venv\lib\site-packages\flashy\__init__.py)
cannot import name 'distrib' from partially initialized module 'flashy' (most likely due to a circular import) (D:\audio-webui\venv\lib\site-packages\flashy\__init__.py)
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues

can you please advice ?

**Comment by gitmylo** [comment]
That's weird, that's a circular import in audiocraft, not my code. Either there's something wrong with your python install, or with audiocraft, and seeing that it hasn't released an update recently. I suggest you try installing a different version of python 3.10, like 3.10.8 for example. If you already do, try reinstalling it.

**Comment by navarisun1982** [comment]
i can't install anything past 3.10.6 cause this may make conflicts with stable diffusion automatic1111
