### ISSUE TITLE
[BUG REPORT] Installation issue

### ISSUE THREAD

**Issue by edouaz** [gitmylo/audio-webui#190]
**Describe the bug**
I executed the run.bat file and encountered an error at the conclusion. Despite restarting the process, the issue persisted. I attempted to reinstall both Hugging Face and PyTorch, yet it had no effect. I am using Windows 11 with an AMD graphics card on a laptop equipped with an AMD processor.

`
```
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Webui version: 40d2a72293b6a6749b21d851b1fb301d6e8684b4 - Fri Dec 1 16:22:35 2023 +0100
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Webui version: 40d2a72293b6a6749b21d851b1fb301d6e8684b4 - Fri Dec 1 16:22:35 2023 +0100
Found extensions:
Done installing/checking installs.
Activating extensions
Preparing
Traceback (most recent call last):
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\main.py", line 44, in <module>
    autodebug.catcher(e)
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\webui\modules\implementations\ttsmodels.py", line 14, in <module>
    import webui.modules.models as mod
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\webui\modules\models.py", line 6, in <module>
    from transformers import Pipeline
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\venv\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\venv\lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\venv\lib\site-packages\transformers\utils\__init__.py", line 61, in <module>
    from .hub import (
  File "C:\Users\edoua\Documents\Voix\audio-webui\audio-webui\venv\lib\site-packages\transformers\utils\hub.py", line 94, in <module>
    PYTORCH_PRETRAINED_BERT_CACHE = os.getenv("PYTORCH_PRETRAINED_BERT_CACHE", constants.HF_HUB_CACHE)
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'
Press any key to continue..
``` `

**Comment by ThePagi** [comment]
Can confirm, I have the same error:

`Traceback (most recent call last):
  File "D:\audio-webui\main.py", line 44, in <module>
    autodebug.catcher(e)
  File "D:\audio-webui\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "D:\audio-webui\main.py", line 26, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "D:\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "D:\audio-webui\webui\modules\implementations\ttsmodels.py", line 14, in <module>
    import webui.modules.models as mod
  File "D:\audio-webui\webui\modules\models.py", line 6, in <module>
    from transformers import Pipeline
  File "D:\audio-webui\venv\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\audio-webui\venv\lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\audio-webui\venv\lib\site-packages\transformers\utils\__init__.py", line 61, in <module>
    from .hub import (
  File "D:\audio-webui\venv\lib\site-packages\transformers\utils\hub.py", line 94, in <module>
    PYTORCH_PRETRAINED_BERT_CACHE = os.getenv("PYTORCH_PRETRAINED_BERT_CACHE", constants.HF_HUB_CACHE)
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'`

I'm on Windows 11 with an AMD processor and Nvidia gpu.

**Comment by gitmylo** [comment]
Pull the new change and check if that fixes it. The change just gives it a new default path, since it looks like the original default path isn't working.

**Comment by gitmylo** [comment]
Does this error only happen on windows?

**Comment by luthis1124** [comment]
This issue should be resolved now.

It has fixed it for me.
