### ISSUE TITLE
[BUG REPORT]  Lock gradio version

### ISSUE THREAD

**Issue by melMass** [gitmylo/audio-webui#193]
**Describe the bug**

While trying to get the server running again I reinstalled it but it won't run anymore.

**To Reproduce**
Install gradio, either manually or using the install script this will install `4.10`

**Expected behavior**
Either lock the gradio req or fix the bug

**Screenshots**

**Additional context**

**Windows 11** 

```sh
2023-12-16 14:01:05 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2023-12-16 14:01:05 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
Traceback (most recent call last):
  File "audio-webui.git\main.py", line 59, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "audio-webui.git\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "audio-webui.git\webui\modules\implementations\ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "audio-webui.git\webui\modules\implementations\patches\bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "audio-webui.git\webui\modules\implementations\patches\bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "audio-webui.git\webui\ui\tabs\__init__.py", line 2, in <module>
    from .text_to_speech import text_to_speech
  File "audio-webui.git\webui\ui\tabs\text_to_speech.py", line 2, in <module>
    from gradio.components import IOComponent
ImportError: cannot import name 'IOComponent' from 'gradio.components' (.venv\lib\site-packages\gradio\components\__init__.py)
cannot import name 'IOComponent' from 'gradio.components' (.venv\lib\site-packages\gradio\components\__init__.py)
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues
```

**Comment by gitmylo** [comment]
Do you know at which version it stopped working?

**Comment by melMass** [comment]
> Do you know at which version it stopped working? 

Unfortunately I don't

> Although audio-webui locks gradio at `3.35.2` the last version that could still work is `3.50.2`.

Thanks let me try now and report

> If you use the built in automatic installer, it will install `3.35.2`.

I avoid automatic stuff since I like to manage my envs but I did follow the paths to makes sure to follow these, may I ask where this is enforced I don't see it?

**Comment by gitmylo** [comment]
The requirement info is stored here: [setup_tools/magicinstaller/requirements/__init__.py](https://github.com/gitmylo/audio-webui/blob/master/setup_tools/magicinstaller/requirements/__init__.py)

**Comment by melMass** [comment]
It works!
I also had to change the port used by torch distributed somehow (it failed to bind otherwise)
And trying the torch-pepe based extraction crashed the server with a symbol not found:

```sh
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
LLVM ERROR: Symbol not found: __svml_cosf8_ha
```
