### ISSUE TITLE
failed to install Pytorch

### ISSUE THREAD

**Issue by chen-wei-lin** [gitmylo/audio-webui#195]
Failed to install PyTorch. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://download.pytorch.org/whl/cu117
Collecting torch
  Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-win_amd64.whl (2343.6 MB)
     --------------------------------         1.9/2.3 GB 785.9 kB/s eta 0:09:16

STDERR:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 509, in read
    with self._error_catcher():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\Downloads\audio-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.

[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 2
I have make an TTS project in the file before and I haved already install pytorch.Is this error anything about this ?

**Comment by gitmylo** [comment]
Check if you can reach https://pytorch.org/

**Comment by yodatak** [comment]
Same for me with fedora 39 silverblue and python 3.10 in distrobox container 

```

⬢[yodatak@toolbox audio-webui]$ ./run.sh 
Checking installs and venv + autodebug checks
Python version:  3.10.13 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions: 
activating venv
no venv found, creating venv
Checking installs and venv + autodebug checks
Python version:  3.10.13 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions: 
Installed packaging!             
Installed numpy!             
Failed to install PyTorch. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://download.pytorch.org/whl/cu117
Collecting torch
  Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl (1843.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 3.0 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu117/torchvision-0.15.2%2Bcu117-cp310-cp310-linux_x86_64.whl (6.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 29.6 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu117/torchaudio-2.0.2%2Bcu117-cp310-cp310-linux_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 17.2 MB/s eta 0:00:00
Collecting filelock (from torch)
  Downloading https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting typing-extensions (from torch)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting sympy (from torch)
  Downloading https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 26.4 MB/s eta 0:00:00
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 25.8 MB/s eta 0:00:00
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 15.5 MB/s eta 0:00:00
Collecting triton==2.0.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 20.6 MB/s eta 0:00:00
Collecting cmake (from triton==2.0.0->torch)
  Downloading https://download.pytorch.org/whl/cmake-3.25.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 28.8 MB/s eta 0:00:00
Collecting lit (from triton==2.0.0->torch)
  Downloading https://download.pytorch.org/whl/lit-15.0.7.tar.gz (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.3/132.3 kB 15.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'




STDERR:
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Looking in indexes: https://download.pytorch.org/whl/cu117
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      
      [notice] A new release of pip is available: 23.2.1 -> 23.3.2
      [notice] To update, run: pip install --upgrade pip
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip



Please read the error above carefully. 
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 1
^CTraceback (most recent call last):
  File "/var/home/yodatak/Projets/Public/audio-webui/main.py", line 19, in <module>
    prelaunch_checks()
  File "/var/home/yodatak/Projets/Public/audio-webui/autodebug/prelaunch.py", line 32, in prelaunch_checks
    ensure_installed()  # Installs missing packages
  File "/var/home/yodatak/Projets/Public/audio-webui/install.py", line 14, in ensure_installed
    install_requirements()
  File "/var/home/yodatak/Projets/Public/audio-webui/setup_tools/magicinstaller/magicinstaller.py", line 5, in install_requirements
    requirement.install_or_upgrade_if_needed()
  File "/var/home/yodatak/Projets/Public/audio-webui/setup_tools/magicinstaller/requirement.py", line 30, in install_or_upgrade_if_needed
    self.post_install(self.install())
  File "/var/home/yodatak/Projets/Public/audio-webui/setup_tools/magicinstaller/requirement.py", line 35, in post_install
    raise InstallFailException(exit_code, stdout, stderr)
autodebug.autodebug.InstallFailException: Install failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/home/yodatak/Projets/Public/audio-webui/main.py", line 45, in <module>
    autodebug.catcher(e)
  File "/var/home/yodatak/Projets/Public/audio-webui/autodebug/autodebug.py", line 65, in catcher
    e.action()
  File "/var/home/yodatak/Projets/Public/audio-webui/autodebug/autodebug.py", line 49, in action
    input()
KeyboardInterrupt
Press any key to exit...

```

**Comment by hggz** [comment]
Ran into this too, had to change torch install under `setup_tools/magicinstaller/requirements/torch_package.py` bottom command to `self.install_pip('torch torchvision torchaudio --extra-index-url...` from `-index-url`

**Comment by CRCODE22** [comment]
I wonder how long it takes for the creator to understand that several reported bugs are related to the same problem. He needs to fix his install scripts.

**Comment by Cry0nicS** [comment]
> Ran into this too, had to change torch install under `setup_tools/magicinstaller/requirements/torch_package.py` bottom command to `self.install_pip('torch torchvision torchaudio --extra-index-url...` from `-index-url`

Just tried this.
However, still getting the same error.

Manually running `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` also hasn't helped.

**Comment by gitmylo** [comment]
I have pushed a commit to change the torch version to 11.8, as suggested by @hggz 
My apologies for my inactivity. I've been very busy with work. The goal was to still keep audio-webui in a functional state, but this hasn't been the case for everyone. And I apologise for this.

Pull requests are always welcome though, and much appreciated.
