### ISSUE TITLE
[BUG REPORT] FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by gourcuff72** [gitmylo/audio-webui#201]
**Describe the bug**
Checking installs and venv + autodebug checks
Python version:  3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.192
9 64 bit (AMD64)]
Traceback (most recent call last):
  File "D:\PortableGit\audio-webui\main.py", line 45, in <module>
    autodebug.catcher(e)
  File "D:\PortableGit\audio-webui\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "D:\PortableGit\audio-webui\main.py", line 19, in <module>
    prelaunch_checks()
  File "D:\PortableGit\audio-webui\autodebug\prelaunch.py", line 30, in prelaunc
h_checks
    print_git()
  File "D:\PortableGit\audio-webui\autodebug\prelaunch.py", line 21, in print_gi
t
    result = subprocess.run(command, capture_output=True)
  File "C:\Users\Freeware Sys\AppData\Local\Programs\Python\Python310\lib\subpro
cess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Freeware Sys\AppData\Local\Programs\Python\Python310\lib\subpro
cess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Freeware Sys\AppData\Local\Programs\Python\Python310\lib\subpro
cess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .

I get this error when i open run.bat. My system is windows 8.1 , Acer aspire notebook with intel gpu

**Comment by gourcuff72** [comment]
Probably it was because of using git - portable, But now i have problem that I cant save TorchPy to my pc because of less memory. How to save it to an usb?
