### ISSUE TITLE
[BUG REPORT] Failed to listen on network address

### ISSUE THREAD

**Issue by Halzouu** [gitmylo/audio-webui#202]
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions:
Done installing/checking installs.
Activating extensions
Preparing
2024-01-09 16:33:59 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-01-09 16:33:59 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-01-09 16:33:59 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
[W ..\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to [Halzou]:51545 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to Halzou:51545 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.).
[E ..\torch\csrc\distributed\c10d\socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\main.py", line 45, in <module>
    autodebug.catcher(e)
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\main.py", line 27, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\modules\implementations\ttsmodels.py", line 15, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\modules\implementations\patches\bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\modules\implementations\patches\bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\ui\tabs\__init__.py", line 7, in <module>
    from .training_tab import training_tab
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\ui\tabs\training_tab.py", line 2, in <module>
    from webui.ui.tabs.training.rvc import train_rvc
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\ui\tabs\training\rvc.py", line 2, in <module>
    import webui.ui.tabs.training.training.rvc_workspace as rvc_ws
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 43, in <module>
    dist.init_process_group(
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\venv\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "C:\Users\c4rs0\Downloads\audio-webui\audio-webui\venv\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [Halzou]:51545 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.). The server socket has failed to bind to Halzou:51545 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.).

**Comment by gitmylo** [comment]
Try rebooting and running again.

**Comment by Halzouu** [comment]
I got the same issue, I tried reinstalling too. It worked before but I don't know what broke it.
