### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by Mandazi39** [gitmylo/audio-webui#203]
I Downloaded the audio-webui.zip from the latest release
extracted to a external ssd, ran the windows installer, then ran the run bat and have gotten this message:

WARNING: Unable to run py command, you probably do not have py launcher installed, make sure you have the python.org version installed, not the windows store version.
Launching anyways, running python command.
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: Unable to check version, not installed with git.
Found extensions:
activating venv
no venv found, creating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: Unable to check version, not installed with git.
Found extensions:
Installed packaging!
Installed numpy!
Installed PyTorch!
Installed transformers!
Installed diffusers!
Installed gradio!
Traceback (most recent call last):
  File "F:\AudioWEBUi\audio-webui\audio-webui\main.py", line 19, in <module>
    prelaunch_checks()
  File "F:\AudioWEBUi\audio-webui\audio-webui\autodebug\prelaunch.py", line 32, in prelaunch_checks
    ensure_installed()  # Installs missing packages
  File "F:\AudioWEBUi\audio-webui\audio-webui\install.py", line 14, in ensure_installed
    install_requirements()
  File "F:\AudioWEBUi\audio-webui\audio-webui\setup_tools\magicinstaller\magicinstaller.py", line 5, in install_requirements
    requirement.install_or_upgrade_if_needed()
  File "F:\AudioWEBUi\audio-webui\audio-webui\setup_tools\magicinstaller\requirement.py", line 29, in install_or_upgrade_if_needed
    if not self.is_installed() or not self.is_right_version():
  File "F:\AudioWEBUi\audio-webui\audio-webui\setup_tools\magicinstaller\requirement.py", line 136, in is_right_version
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
No module named 'packaging'
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues

I ran an earlier version before with no issues. 

I've tried also the git pull install with the exact same behavior after running the bat.

**Comment by gitmylo** [comment]
Please use the installer: https://github.com/gitmylo/audio-webui/releases it should install the latest version. Since it looks like you just downloaded the zip from the repo. This may not be the cause of the issue, But it's better to use the installer.
