### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by Da04x** [gitmylo/audio-webui#204]
Trying to install the program for text to speech but get the following error:

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (2.1.0)
Requirement already satisfied: torchvision in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (0.15.2+cu117)
Requirement already satisfied: torchaudio in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (2.1.0)
Requirement already satisfied: filelock in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (4.9.0)
Requirement already satisfied: fsspec in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (2023.12.2)
Requirement already satisfied: sympy in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (1.12)
Requirement already satisfied: jinja2 in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: networkx in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torch) (3.0)
Requirement already satisfied: numpy in c:\users\daniy\downloads\audio-webui\audio-webui\venv\lib\site-packages (from torchvision) (1.23.5)
Collecting torch

STDERR:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 125, in unpackb
    ret = unpacker._unpack()
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\daniy\Downloads\audio-webui\audio-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 603, in _unpack
    return bytes(obj)
MemoryError

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip"

Any help would be appreciated

**Comment by gitmylo** [comment]
Try running it again, it might work. Looks like it ran out of memory there.

**Comment by Da04x** [comment]
> Try running it again, it might work. Looks like it ran out of memory there.

Yh it works. How long will it take for the text to speech to load?

**Comment by Da04x** [comment]
> Try running it again, it might work. Looks like it ran out of memory there.

**Comment by Da04x** [comment]
The text to speech is taking forever to load and there is no loading bar
