### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by dfilter** [gitmylo/audio-webui#212]
**Describe the bug**
When running the setup.bat file python throws an ImportError

**To Reproduce**
Run the provided "install_windows.bat"
Run "setup.bat" in project root

**Expected behavior**
The webui to start up.

`Checking installs and venv + autodebug checks
Python version:  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions:
Installed PyTorch!
Done installing/checking installs.
Activating extensions
Preparing
Traceback (most recent call last):
  File "E:\audio-webui\main.py", line 27, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "E:\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "E:\audio-webui\webui\modules\implementations\ttsmodels.py", line 5, in <module>
    import gradio
  File "E:\audio-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\audio-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\audio-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (E:\audio-webui\venv\lib\site-packages\gradio_client\documentation.py)
cannot import name 'set_documentation_group' from 'gradio_client.documentation' (E:\audio-webui\venv\lib\site-packages\gradio_client\documentation.py)
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues`

**Additional context**
Running windows 11
Have Miniconda3 installed and python3.9 however python --version yeilds "3.10.8"

**Comment by davidgovea** [comment]
Also experiencing this. First with conda & python 3.10, then also on a fresh install using system 3.10 and the official installer

**Comment by michalin** [comment]
I'm having that on the Colab notebook as well

**Comment by pawix135** [comment]
Same issue here. Windows 10, python 3.10.11

**Comment by Miko42** [comment]
I had the same issue. it worked:
pip install gradio_client==0.8.0

paste in activate_only.bat

**Comment by pawix135** [comment]
@Miko42 It worked! Thanks!

**Comment by dfilter** [comment]
> I had the same issue. it worked: pip install gradio_client==0.8.0 paste in activate_only.bat or !pip install gradio_client==0.8.0 on google colab

This solution worked for me.

**Comment by perkel666** [comment]
I solved it importing older version:

`git checkout @{50.days.ago}`

add it after `git pull` to update.bat

**Comment by gitmylo** [comment]
@Miko42 Thank you for the suggestion, it's been added to the requirements and should work automatically now.
