### ISSUE TITLE
[BUG REPORT] Forever loading, without any output (Similar to issue #199?)

### ISSUE THREAD

**Issue by ThisFace** [gitmylo/audio-webui#213]
Describe the bug
I can run run.bat, it fetches the URL, and I can access the site but whenever I try to do something, it just stays in a loading cycle.
It looks similar to the 

To Reproduce

    Go to any of the tools
    Click or Interact with any of tools
    Wait forever in a queue (Ctrl C & V from issue #199)

Expected behavior
Either show any error or succeed in processing the queue and being able to use the tools.

Additional context
RTX 3090 24gb
Installed with auto installer on C drive
Cuda 12.1

I'll try to provide any additional information needed to resolve the situation.

**Comment by ThisFace** [comment]
Oops, sorry! Forgot to add the text.

Here's what it says when I launch the run.bat.

`Checking installs and venv + autodebug checks
Python version:  3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Webui version: bcbba0774e0d9d701714bc3546046b922c331b84 - Sat Dec 16 14:16:53 2023 +0100
Found extensions:
Done installing/checking installs.
Activating extensions
Preparing
2024-02-09 13:24:15 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-02-09 13:24:15 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.0.1+cu117)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-02-09 13:24:15 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-02-09 13:24:15 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
Monkeypatching bark
Monkeypatching gradio
Launching, cuda available: True
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.`


And this text pops up whenever I try to activate anything in the provided URL.

`2024-02-09 13:25:52 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='4rce37j4esj_8' coro=<Queue.process_events() done, defined at C:\audio-webui\audio-webui\venv\lib\site-packages\gradio\queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['', '', None, '...on_hash': '4rce37j4esj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing>
Traceback (most recent call last):
  File "C:\audio-webui\audio-webui\venv\lib\site-packages\gradio\queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\audio-webui\audio-webui\venv\lib\site-packages\gradio\queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\audio-webui\audio-webui\venv\lib\site-packages\gradio\queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "C:\audio-webui\audio-webui\venv\lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['', '', None, '...on_hash': '4rce37j4esj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing`

**Comment by tilllt** [comment]
I think this repo is broken ATM, i get the same error:
`
2024-02-14 07:34:35 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='qqg3wx812us_6' coro=<Queue.process_events() done, defined at /docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['suno/bark'], '...on_hash': 'qqg3wx812us'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing>
Traceback (most recent call last):
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['suno/bark'], '...on_hash': 'qqg3wx812us'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
2024-02-14 07:46:13 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='qqg3wx812us_23' coro=<Queue.process_events() done, defined at /docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['melodic ambien...on_hash': 'qqg3wx812us'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing>
Traceback (most recent call last):
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/docker/audio-webui/venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['melodic ambien...on_hash': 'qqg3wx812us'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
`

**Comment by Iminy99** [comment]
I have the exact same problem, how can I fix it?
