### ISSUE TITLE
[BUG REPORT] cant download or cant strip audio

### ISSUE THREAD

**Issue by wizzer48** [gitmylo/audio-webui#222]
**Describe the bug**
when i try to strip audio from video, i get this error:
down() is not in the list of choices. Please update the list of choices to include: Deneme or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "C:\dene\audio-webui\webui\modules\implementations\ffmpeg_utils.py", line 71, in strip
    result = run_command(f'ffmpeg -y -i "{a.name}" "{out_file}"')
  File "C:\dene\audio-webui\webui\modules\implementations\ffmpeg_utils.py", line 14, in run_command
    return subprocess.run(command)
  File "C:\Users\atlas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\atlas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\atlas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor
**Other Bug**
when i try to download from youtube, i get this error:

Traceback (most recent call last):
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\dene\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\dene\audio-webui\venv\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "C:\dene\audio-webui\webui\modules\implementations\audio_download.py", line 14, in download_audio
    ffmpeg
  File "C:\dene\audio-webui\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\dene\audio-webui\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\atlas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\atlas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor

**Comment by gitmylo** [comment]
Install [ffmpeg](https://ffmpeg.org/) on a system path. (The same dir as audio-webui might work as well)

[Download](https://github.com/BtbN/FFmpeg-Builds/releases) an ffmpeg release (you probably want [ffmpeg-master-latest-win64-gpl-shared.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip))

# Same dir as audio-webui (ffmpeg will not be available from other programs)
Open the zip, and drag the `contents` of the `bin` folder into your audio-webui directory.

# System-wide (windows path) (NOT RECOMMENDED)
Open the zip, and drag the `contents` of the `bin` folder into your `C:/windows/` folder, this is not recommended because it is harder to uninstall.

# System-wide (new value in path)
Create a folder anywhere that you want to make available to all programs.
[Add this folder to your path](https://stackoverflow.com/a/44272417)
Open the zip, and drag the `contents` of the `bin` folder into your folder you added to the path.

# After installing ffmpeg
Relaunch the webui.
