### ISSUE TITLE
[BUG REPORT] Install process constantly overwrites huggingface-hub to 0.19.0 and cannot continue

### ISSUE THREAD

**Issue by Skrownerve** [gitmylo/audio-webui#231]
**Describe the bug**
When running run.sh to install and run, huggingface-hub is installed and overwrites whatever version I currently have in site-packages for Python 3.10 with huggingface-hub version 0.19.4. Then, I get the following:
`ImportError: huggingface-hub>=0.23.0,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.4.`
I believe this is coming from Transformers. I can remove 0.19.4 and install the version this message is telling me to, but it is always overwritten by 0.19.4 during the install.

**To Reproduce**
1. Run run.sh
2. Watch 0.19.4 get installed
3. Receive error

**Expected behavior**
I am fairly new to Linux and not a programmer. What I expect to happen here is the install process to install what it needs and then run the application. I am not expecting to see it install an incorrect version of a component and then complain to me about it!

**Additional context**
I have tried my best to look through as many files as I can to see where this version of huggingface-hub is being installed, but I was unable to find it. I have no clue if this is really the base issue. I cannot use --skip-install because bark (and likely other requirements) is never installed properly due to this error, and the installer then complains about that. I even tried removing Transformers in case a prior version I had was the cause. But then it's reinstalled during this process and it all still happens.
Here is the entire log from start to finish:
`./run.sh
Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Webui version: 7eb428accafc56d3836ee6b399fa9f852ac75f89 - Fri Feb 16 19:25:22 2024 +0100
Found extensions: 
Installed wheel!             
Installed diffusers!             
Installed huggingface-hub!             
Installed bark!             
Done installing/checking installs.
Activating extensions
Preparing
Traceback (most recent call last):
  File "/home/trie/Music/voice/RVC/audio-webui/main.py", line 27, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/home/trie/Music/voice/RVC/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/home/trie/Music/voice/RVC/audio-webui/webui/modules/implementations/ttsmodels.py", line 14, in <module>
    import webui.modules.models as mod
  File "/home/trie/Music/voice/RVC/audio-webui/webui/modules/models.py", line 6, in <module>
    from transformers import Pipeline
  File "/home/trie/.local/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/trie/.local/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "/home/trie/.local/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "/home/trie/.local/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/home/trie/.local/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: huggingface-hub>=0.23.0,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.4.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main
huggingface-hub>=0.23.0,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.4.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues`

**Comment by gitmylo** [comment]
I have set the required version number the 0.23.0, as specified in transformers' requirements [here](https://github.com/huggingface/transformers/blob/b6eb708bf1903f40499558b64e6d9392c1b889e1/setup.py#L120).

If this commit causes issues, tell me, and I'll find an alternative solution. If it works, then you can just close the issue.

**Comment by AMacholl** [comment]
I went to audio-webui\venv\Lib\site-packages\huggingface_hub-0.23.0.dist-info\metadata and just changed the version to 0.23.4 and it worked
