### ISSUE TITLE
[BUG REPORT] The Installation fails

### ISSUE THREAD

**Issue by Orfey1** [gitmylo/audio-webui#234]
**Describe the bug**
I can't complete the installation of UI by running run.bat, it always fails.

**To Reproduce**
1. Go to audio-webui folder.
2. Click on run.bat
3. See error: Install failed!

**Expected behavior**
Intallation fails each time and you can not run audio-ui

**Screenshots**
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
activating venv
no venv found, creating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
Installed packaging!
Installed wheel!
Installed numpy!
Failed to install PyTorch. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.1.0
  Downloading https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
     ---------------------------------------- 2.7/2.7 GB 579.5 kB/s eta 0:00:00
Collecting torchvision==0.16.0
  Downloading https://download.pytorch.org/whl/cu118/torchvision-0.16.0%2Bcu118-cp310-cp310-win_amd64.whl (5.0 MB)
     ---------------------------------------- 5.0/5.0 MB 22.9 MB/s eta 0:00:00
Collecting torchaudio==2.1.0
  Downloading https://download.pytorch.org/whl/cu118/torchaudio-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (3.9 MB)
     ---------------------------------------- 3.9/3.9 MB 62.0 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 3.9 MB/s eta 0:00:00
Collecting fsspec
  Using cached fsspec-2024.6.1-py3-none-any.whl (177 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting jinja2
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting sympy
  Using cached sympy-1.12.1-py3-none-any.whl (5.7 MB)
Collecting filelock
  Using cached filelock-3.15.4-py3-none-any.whl (16 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached pillow-10.4.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Requirement already satisfied: numpy in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchvision==0.16.0) (1.23.5)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.7-py3-none-any.whl (66 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
     ---------------------------------------- 163.0/163.0 kB ? eta 0:00:00
Collecting mpmath<1.4.0,>=1.1.0
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchaudio

STDERR:
ERROR: Exception:
Traceback (most recent call last):
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 461, in run
    installed = install_given_reqs(
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\req\req_install.py", line 790, in install
    install_wheel(
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 727, in install_wheel
    _install_wheel(
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 587, in _install_wheel
    file.save()
  File "E:\AI15\AIVOICE\!audio webui\audio-webui\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 386, in save
    with self._zip_file.open(zipinfo) as f:
  File "C:\Users\Dibak\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1556, in open
    raise BadZipFile(
zipfile.BadZipFile: File name in directory (1980, 1, 1, 0, 0, 0) and header b'torch/include/ATen/ops/_prelu_kernel_cuda_dispatch.h' differ.

[notice] A new release of pip available: 22.2.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 2

**Additional context**
-

**Comment by gitmylo** [comment]
Can you run activate_only.bat, then run the command `pip install --no-cache-dir torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --extra-index-url https://download.pytorch.org/whl/cu118`

The cause for the error could be a corrupt torch wheel in `%LocalAppData%\pip\Cache`, by installing with `--no-cache-dir` the cached wheel will be ignored. Although according to the logs, it did try to download it, regardless, it appears the cause of the error is a corrupt torch wheel.

**Comment by Orfey1** [comment]
> Can you run activate_only.bat, then run the command `pip install --no-cache-dir torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --extra-index-url https://download.pytorch.org/whl/cu118`
> 
> The cause for the error could be a corrupt torch wheel in `%LocalAppData%\pip\Cache`, by installing with `--no-cache-dir` the cached wheel will be ignored. Although according to the logs, it did try to download it, regardless, it appears the cause of the error is a corrupt torch wheel.

Hey, thanks a lot for a quick reply. Honestly I'm really new to this and I barely know what's going on. I did like you've said and clicked activate.bat, then I run the command inside:
`pip install --no-cache-dir torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --extra-index-url https://download.pytorch.org/whl/cu118`

I've got a bunch of messages that requirements are already satisfied but in the end the successful installation message:
```
Installing collected packages: torch, torchvision, torchaudio
Successfully installed torch-2.1.0+cu118 torchaudio-2.1.0+cu118 torchvision-0.16.0+cu118
```
Apologies if that's a stupid question, but where do you add the line --no-cache-dir ? 

After running the command in activate.bat you've showed me the installation still failed displaying the message:

```
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
Installed wheel!
Installed transformers!
Installed diffusers!
Installed gradio!
Installed huggingface-hub!
Installed audio2numpy!
Installed bark!
Installed soundfile!
Installed audiolm!
Installed praat-parselmouth!
Installed pyworld!
Installed faiss!
Failed to install torchcrepe. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Collecting torchcrepe==0.0.20
  Downloading torchcrepe-0.0.20-py3-none-any.whl (72.3 MB)
     --------------------------------------- 72.3/72.3 MB 24.2 MB/s eta 0:00:00
Requirement already satisfied: torch in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchcrepe==0.0.20) (2.1.0+cu118)
Requirement already satisfied: tqdm in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchcrepe==0.0.20) (4.66.4)
Collecting resampy
  Downloading resampy-0.4.3-py3-none-any.whl (3.1 MB)
     ---------------------------------------- 3.1/3.1 MB 49.5 MB/s eta 0:00:00
Requirement already satisfied: scipy in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchcrepe==0.0.20) (1.14.0)
Collecting librosa==0.9.1
  Downloading librosa-0.9.1-py3-none-any.whl (213 kB)
     ---------------------------------------- 213.1/213.1 kB ? eta 0:00:00
Collecting decorator>=4.0.10
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: packaging>=20.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from librosa==0.9.1->torchcrepe==0.0.20) (24.1)
Collecting pooch>=1.0
  Using cached pooch-1.8.2-py3-none-any.whl (64 kB)
Collecting audioread>=2.1.5
  Using cached audioread-3.0.1-py3-none-any.whl (23 kB)
Requirement already satisfied: numpy>=1.17.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from librosa==0.9.1->torchcrepe==0.0.20) (1.23.5)
Requirement already satisfied: scikit-learn>=0.19.1 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from librosa==0.9.1->torchcrepe==0.0.20) (1.5.1)
Requirement already satisfied: soundfile>=0.10.2 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from librosa==0.9.1->torchcrepe==0.0.20) (0.12.1)




STDERR:



Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 3221225477
```
I found the same error on the issue report here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13659
I did what a person in comments suggested and run:
```
pip install clip
pip install open_clip_torch[training]
```
Whatever that is, it installed successfuly. Not sure if I did that right, but I've opened cmd inside the main audio-webui folder and run those two commands inside. After installation of those pip clip things, and running run.bat it still did not work, I received a similar message to the first one I've posted here but with Exit code:1 instead of Exit code:2, posting the full message:

```
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
Installed wheel!
Installed huggingface-hub!
Installed torchcrepe!
Installed ffmpeg-python!
Installed noisereduce!
Installed demucs!
Installed pytube!
Installed openai-whisper!
Failed to install audiocraft. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Collecting audiocraft>=1.0.0
  Downloading audiocraft-1.3.0.tar.gz (635 kB)
     -------------------------------------- 635.7/635.7 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting av==11.0.0
  Downloading av-11.0.0-cp310-cp310-win_amd64.whl (25.9 MB)
     --------------------------------------- 25.9/25.9 MB 28.4 MB/s eta 0:00:00
Requirement already satisfied: einops in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from audiocraft>=1.0.0) (0.8.0)
Collecting flashy>=0.0.1
  Downloading flashy-0.0.2.tar.gz (72 kB)
     ---------------------------------------- 72.4/72.4 kB ? eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'




STDERR:
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 3221225477

  [0 lines of output]
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 3221225477

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip



Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 1
```

**Comment by gitmylo** [comment]
> Apologies if that's a stupid question, but where do you add the line --no-cache-dir
It was already in the command I listed, I just mentioned it to reference it

If you ran `pip install open_clip_torch[training]`, it will most likely have installed the cpu-only version of pytorch
`pip install --upgrade --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` will install a newer version of torch with cuda (for nvidia gpu) support. You could try that.

As for audiocraft, I'm not really sure

**Comment by Orfey1** [comment]
Sadly I still get the same error with the same error code after running:
`pip install --upgrade --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 `

```
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
activating venv
Checking installs and venv + autodebug checks
Python version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Webui version: 17c7489a1ffb1a95ac6e600af25383b7b07f3909 - Wed May 29 16:37:24 2024 +0200
Found extensions:
Installed wheel!
Failed to install PyTorch. Check AutoDebug output.

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.1.0
  Using cached https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
Requirement already satisfied: torchvision==0.16.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (0.16.0+cu118)
Collecting torchaudio==2.1.0
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (3.9 MB)
Requirement already satisfied: filelock in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (3.15.4)
Requirement already satisfied: jinja2 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (3.1.4)
Requirement already satisfied: sympy in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (1.12.1)
Requirement already satisfied: fsspec in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (2024.6.1)
Requirement already satisfied: networkx in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (3.3)
Requirement already satisfied: typing-extensions in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torch==2.1.0) (4.12.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchvision==0.16.0) (10.4.0)
Requirement already satisfied: requests in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchvision==0.16.0) (2.32.3)
Requirement already satisfied: numpy in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from torchvision==0.16.0) (1.23.5)
Requirement already satisfied: MarkupSafe>=2.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from jinja2->torch==2.1.0) (2.1.5)
Requirement already satisfied: certifi>=2017.4.17 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from requests->torchvision==0.16.0) (2024.7.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from requests->torchvision==0.16.0) (2.2.2)
Requirement already satisfied: idna<4,>=2.5 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from requests->torchvision==0.16.0) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from requests->torchvision==0.16.0) (3.3.2)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in e:\ai15\aivoice\!audio webui\audio-webui\venv\lib\site-packages (from sympy->torch==2.1.0) (1.3.0)
Installing collected packages: torch, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1
    Uninstalling torch-2.0.1:
      Successfully uninstalled torch-2.0.1

STDERR:

Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 3221225477
```
