### ISSUE TITLE
[BUG REPORT] After latest update RVC doesn't work anymore

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#52]
Updated to latest version. When I try to generate anything with RVC I get these errors:

`TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

`if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'`

**Comment by gitmylo** [comment]
do you have ffprobe (comes with ffmpeg) installed? i believe this happens when the command isn't found.

**Comment by nekogecko2** [comment]
I have both ffmpeg and ffprobe in the program's directory.  I reinstalled the program in a new folder and I'm still getting the same errors with RVC.

**Comment by gitmylo** [comment]
can you send more log from the error then?

**Comment by nekogecko2** [comment]
Traceback (most recent call last):
  File "E:\BARK_gitmylo2\audio-webui\webui\modules\implementations\rvc\rvc.py", line 226, in vc_single
    audio_opt = vc.pipeline(
  File "E:\BARK_gitmylo2\audio-webui\webui\modules\implementations\rvc\vc_infer_pipeline.py", line 250, in pipeline
    and os.path.exists(file_index) == True
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Traceback (most recent call last):
  File "E:\BARK_gitmylo2\audio-webui\webui\modules\implementations\rvc\rvc.py", line 226, in vc_single
    audio_opt = vc.pipeline(
  File "E:\BARK_gitmylo2\audio-webui\webui\modules\implementations\rvc\vc_infer_pipeline.py", line 250, in pipeline
    and os.path.exists(file_index) == True
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Traceback (most recent call last):
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\BARK_gitmylo2\audio-webui\webui\ui\tabs\rvc.py", line 147, in gen
    return [audio_tuple, util.make_waveform(audio_tuple), background, audio]
  File "E:\BARK_gitmylo2\audio-webui\webui\modules\util.py", line 61, in make_waveform
    return gradio.make_waveform(audio, bg_color=bg_color, bg_image=bg_image, fg_alpha=fg_alpha, bars_color=bars_color, bar_count=bar_count, bar_width=bar_width)
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\helpers.py", line 744, in make_waveform
    processing_utils.audio_to_file(audio[0], audio[1], tmp_wav.name, format="wav")
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\processing_utils.py", line 156, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "E:\BARK_gitmylo2\audio-webui\venv\lib\site-packages\gradio\processing_utils.py", line 170, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by gitmylo** [comment]
Where is the model located? And what other files does it have around it?

**Comment by gitmylo** [comment]
I've managed to reproduce it, it seems to happen when the index file is missing from the model, i'll check if i can somehow fix the index file detection

**Comment by gitmylo** [comment]
Yeah, it was setting it to None because that's the value i gave it as the backup, which it uses when the path to the index file is empty. So i changed it to an empty string.

(Still, if you trained this model yourself, create an index. it's much better)

**Comment by nekogecko2** [comment]
Thanks for adding .index file support! 😄 I'm just a little confused about how to load it. Does it need to be in the same folder as the model within the /data/ directory? Or does it need to share the same name as the model?  for example

>voicemodel1.pth
>voicemodel1_added.index

I think it might be easier for new users if there was a separate dropdown menu for selecting .index files, like there is for RVC models. It might make it a little less confusing for anyone coming from the rvc-webui

**Comment by gitmylo** [comment]
It will automatically detect an index file if there's any index file in the same directory as the model (if it's in a subdirectory, as models directly in /data/models/rvc aren't supported)

it will search for every index file it finds, and prefers index files with added, as they contain the full info. So it will automatically detect it basically. i could maybe add a feature where you upload a zip and it automatically unzips it and finds both the index and the model, and puts those in the folder.
