### ISSUE TITLE
[BUG REPORT] RuntimeError when cloning Bark model

### ISSUE THREAD

**Issue by patrickmac110** [gitmylo/audio-webui#57]
**Describe the bug**
When trying to clone a voice for bark I get the following error

Extracting semantics
Tokenizing semantics
Traceback (most recent call last):
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\gradio\helpers.py", line 602, in tracked_fn
    response = fn(*args)
  File "A:\Desktop\00 AI Images\audio-webui\webui\ui\tabs\text_to_speech.py", line 81, in _generate
    response, file = loader.get_response(*inputs, progress=progress)
  File "A:\Desktop\00 AI Images\audio-webui\webui\modules\implementations\ttsmodels.py", line 210, in get_response
    _speaker = self.create_voice(temp_file.name, clone_model)
  File "A:\Desktop\00 AI Images\audio-webui\webui\modules\implementations\ttsmodels.py", line 42, in create_voice
    fine_prompt = generate_fine_from_wav(file)
  File "A:\Desktop\00 AI Images\audio-webui\webui\modules\implementations\patches\bark_custom_voices.py", line 88, in generate_fine_from_wav
    encoded_frames = model.encode(wav)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\encodec\model.py", line 144, in encode
    encoded_frames.append(self._encode_frame(frame))
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\encodec\model.py", line 161, in _encode_frame
    emb = self.encoder(x)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\encodec\modules\seanet.py", line 144, in forward
    return self.model(x)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\encodec\modules\conv.py", line 210, in forward
    return self.conv(x)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\encodec\modules\conv.py", line 120, in forward
    x = self.conv(x)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "A:\Desktop\00 AI Images\audio-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by gitmylo** [comment]
Solved in #64, cpu offloading issue. Should work fine now!
