### ISSUE TITLE
Install of TTS fails

### ISSUE THREAD

**Issue by LukasBrauschHFU** [gitmylo/audio-webui#72]
I ran the installer and every time it gets to the install of TTS it prints out the following error:

> Failed to install TTS. Check AutoDebug output.
Traceback (most recent call last):
  File "C:\Users\Lukas\Desktop\audio\audio-webui\install.py", line 15, in <module>
    ensure_installed()
  File "C:\Users\Lukas\Desktop\audio\audio-webui\install.py", line 11, in ensure_installed
    install_requirements()
  File "C:\Users\Lukas\Desktop\audio\audio-webui\setup_tools\magicinstaller\magicinstaller.py", line 4, in install_requirements
    requirement.install_or_upgrade_if_needed()
  File "C:\Users\Lukas\Desktop\audio\audio-webui\setup_tools\magicinstaller\requirement.py", line 30, in install_or_upgrade_if_needed
    self.post_install(self.install())
  File "C:\Users\Lukas\Desktop\audio\audio-webui\setup_tools\magicinstaller\requirement.py", line 36, in post_install
    raise InstallFailException(exit_code, stdout, stderr)
autodebug.autodebug.InstallFailException: Install failed!
Press any key to continue . . .

**Comment by gitmylo** [comment]
It would be helpful if you included your autodebug output. As it includes the error, and usually also the fix.

**Comment by LukasBrauschHFU** [comment]
I forgot the C++ tools, my bad
