### ISSUE TITLE
Pyworld undefined symbol: PyVectorcall_Function

### ISSUE THREAD

**Issue by daoso** [gitmylo/audio-webui#80]
Hi, I am getting this while trying to run:

Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Jun 28 2023, 17:56:55) [GCC]
Webui version: 0fd174d515fb53f4c119506b5b1411fc1e3cc7d5 - Tue Jul 18 20:57:17 2023 +0200
activating venv
no venv found, creating venv
Checking installs and venv + autodebug checks
Python version:  3.10.12 (main, Jun 28 2023, 17:56:55) [GCC]
Webui version: 0fd174d515fb53f4c119506b5b1411fc1e3cc7d5 - Tue Jul 18 20:57:17 2023 +0200
Installed packaging!             
Installed numpy!             
Installed PyTorch!             
Installed transformers!             
Installed diffusers!             
Installed gradio!             
Installed audio2numpy!             
Installed bark!             
Installed sox!             
Installed audiolm!             
Installed praat-parselmouth!             
Installed pyworld!             
Installed faiss!             
Installed torchcrepe!             
Installed ffmpeg-python!             
Installed noisereduce!             
Installed demucs!             
Installed TTS!             
Installed pytube!             
Installed openai-whisper!             
Installed audiocraft!             
Done installing/checking installs.
Preparing
2023-07-21 17:28:58 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-07-21 17:28:59 | WARNING | xformers | Blocksparse is not available: the current GPU does not expose Tensor cores
/audio-webui/venv/lib64/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "/audio-webui/main.py", line 19, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "/audio-webui/webui/modules/implementations/__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "/audio-webui/webui/modules/implementations/ttsmodels.py", line 14, in <module>
    from webui.modules.implementations.patches.bark_custom_voices import wav_to_semantics, generate_fine_from_wav, \
  File "/audio-webui/webui/modules/implementations/patches/bark_custom_voices.py", line 8, in <module>
    from webui.modules.implementations.patches.bark_generation import generate_text_semantic_new, generate_coarse_new, generate_fine_new
  File "/audio-webui/webui/modules/implementations/patches/bark_generation.py", line 7, in <module>
    from webui.ui.tabs import settings
  File "/audio-webui/webui/ui/tabs/__init__.py", line 7, in <module>
    from .training_tab import training_tab
  File "/audio-webui/webui/ui/tabs/training_tab.py", line 2, in <module>
    from webui.ui.tabs.training.rvc import train_rvc
  File "/audio-webui/webui/ui/tabs/training/rvc.py", line 2, in <module>
    import webui.ui.tabs.training.training.rvc_workspace as rvc_ws
  File "/audio-webui/webui/ui/tabs/training/training/rvc_workspace.py", line 32, in <module>
    from webui.modules.implementations.rvc.custom_pitch_extraction import pitch_extract as pe
  File "/audio-webui/webui/modules/implementations/rvc/custom_pitch_extraction.py", line 4, in <module>
    import pyworld
  File "/audio-webui/venv/lib64/python3.10/site-packages/pyworld/__init__.py", line 17, in <module>
    from .pyworld import *
ImportError: /audio-webui/venv/lib64/python3.10/site-packages/pyworld/pyworld.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyVectorcall_Function
/audio-webui/venv/lib64/python3.10/site-packages/pyworld/pyworld.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyVectorcall_Function
Your install might have failed to install one of the requirements, are you missing a package?

To Reproduce:
Opensuse Tumbleweed with latest updates
Running run.sh

Tried:
Installing pyworld from source
Older version of pyworld
--no-binary and --no-build-isolation install arguments

I'm really excited to start using this webui. Thank you for creating and maintaining it, and I hope it's going to become the automatic1111 for audio generation!

**Comment by gitmylo** [comment]
The install still works for me, make sure you're up to date, and make sure you tried running twice, as it might not always install correctly on the first try.

**Comment by daoso** [comment]
Thank you for taking time to look into this 

Everything seems to be up to date, and indeed I tried a few times to install from scratch, also asked AIs to help, to no avail sadly

**Comment by gitmylo** [comment]
Try python 3.10.8, you can still compile from source. Make sure to set it as your base python 3.10 interpreter

**Comment by gitmylo** [comment]
Did you get it working?

**Comment by onasre** [comment]
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Traceback (most recent call last):
  File "C:\audio-webui-master\main.py", line 38, in <module>
    autodebug.catcher(e)
  File "C:\audio-webui-master\autodebug\autodebug.py", line 79, in catcher
    raise e
  File "C:\audio-webui-master\main.py", line 15, in <module>
    prelaunch_checks()
  File "C:\audio-webui-master\autodebug\prelaunch.py", line 30, in prelaunch_checks
    print_git()
  File "C:\audio-webui-master\autodebug\prelaunch.py", line 21, in print_git
    result = subprocess.run(command, capture_output=True)
  File "C:\Users\Omar\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Omar\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Omar\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .

**Comment by gitmylo** [comment]
Delete your venv folder, you cannot switch from linux to windows without deleting the venv folder

**Comment by gitmylo** [comment]
@onasre Do you have git installed? It's the first thing in the readme

**Comment by onasre** [comment]
> Do you have git installed

Oops !  Thx

**Comment by onasre** [comment]
all working , but Training Module gives error , 
`gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
<All keys matched successfully>
D:\audio-webui\audio-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
D:\audio-webui\audio-webui\venv\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ..\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\audio-webui\audio-webui\venv\lib\site-packages\torch\amp\autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "D:\audio-webui\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 683, in train_model
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\parallel\distributed.py", line 1113, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\audio-webui\audio-webui\webui\modules\implementations\rvc\infer_pack\models.py", line 742, in forward
    o = self.dec(z_slice, pitchf, g=g)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\audio-webui\audio-webui\webui\modules\implementations\rvc\infer_pack\models.py", line 495, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\audio-webui\audio-webui\webui\modules\implementations\rvc\infer_pack\models.py", line 418, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\audio-webui\audio-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype`

**Comment by gitmylo** [comment]
Which version of CUDA do you have installed? pytorch can't detect it it seems, it uses CUDA 1.17

**Comment by onasre** [comment]
latest release v12.2

**Comment by onasre** [comment]
By the way when i installed CUDA 12.2  ,, the installation done but with this Note .

Installed:
     - Nsight Monitor
Not Installed:
     - Nsight for Visual Studio 2022
       Reason: VS2022 was not found
     - Nsight for Visual Studio 2019
       Reason: VS2019 was not found
     - Nsight for Visual Studio 2017
       Reason: VS2017 was not found
     - Integrated Graphics Frame Debugger and Profiler
       Reason: see https://developer.nvidia.com/nsight-vstools
     - Integrated CUDA Profilers
       Reason: see https://developer.nvidia.com/nsight-vstools

**Comment by onasre** [comment]
i Have a module i already trained using google colab , how can i add it manually to venv folder ..

**Comment by gitmylo** [comment]
> i Have a module i already trained using google colab , how can i add it manually to venv folder ..

Do you mean a model? It's in the data/training/RVC, or data/models/RVC if you already clicked the move model button

**Comment by onasre** [comment]
yes ,thanks , got it .. still though won't let me train model ..

**Comment by gitmylo** [comment]
I'll close the issue, reopen it if you're still having this issue after updating.
